#!/usr/bin/env bash

comment() {
	echo -e "\e[38;5;246;03m# ${*}\e[39;00m"
}

_random() {
	echo $(( (RANDOM % $2) + $1 ))
}

devices() {
	comment "Here we get a list of devices in fastboot mode connected to the computer"
	comment "Make sure your device is listed here"
	echo "53657269616C206E        fastboot"
}

reboot() {
	if [[ "${1}" == "fastboot" ]]
	then
		comment "Using 'fastboot reboot fastboot' reboots device in FastbootD, which allows us to flash partitions contained in 'super' part"
		echo "Rebooting into fastboot                            OKAY [  0.001s]"
		echo "< waiting for any device >"
		echo "Finished. Total time: 12.280s"
	elif [[ "${1}" == "bootloader" ]]
	then
		comment "We reboot in \"classic\" (bootloader) fastboot mode for wiping userdata"
		echo "Rebooting into bootloader                            OKAY [  1.001s]"
		echo "Finished. Total time: 1.005s"
	fi
}

erase() {
	if [[ "${1}" == "userdata" ]]
	then
		comment "This command will wipe ALL YOUR DATA AND APPS!"
	fi
	echo "Erasing '${1}'    	                            OKAY [  0.123s]"
	echo "Finished. Total time: 0.176s"
}

flash() {
	if [[ "${1}" == "system" ]]
	then
		comment "We flash the system partition with image ${2}"
		comment "This may take several minutes"
		for SPARSE in {1..9}
		do
			echo "Sending sparse 'system' ${SPARSE}/9 ($(_random 110000 150000) KB)                 OKAY [  $(_random 10 9).0$(_random 10 95)s]"
			sleep 1
			echo "Writing 'system'                                        OKAY [  $(_random 0 2).0$(_random 10 75)s]"
			sleep 1
		done
		echo "Finished. Total time: 120.58s"
	fi
}

eval $*
echo ""
# vim: set ft=bash
