#!/usr/bin/env bash

devices() {
	echo "$(/usr/bin/adb shell getprop ro.serialno)        fastboot"
}

reboot() {
	if [[ "${1}" == "fastboot" ]]
	then
		echo "Rebooting into fastboot                            OKAY [  0.001s]"
		echo "< waiting for any device >"
		echo "Finished. Total time: 12.280s"
	fi
}
eval $*
# vim: set ft=bash
